@BASE_URL = http://localhost:2500
@TOKEN = 1

# Welcome Test
GET {{BASE_URL}}/
###

# Welcome to  apple quality Test
GET {{BASE_URL}}/apple/get
###

#
POST {{BASE_URL}}/apple/add
###

#
GET {{BASE_URL}}/bike/get
### 

#
GET {{BASE_URL}}/cow/blue
###

# Add Students details
POST {{BASE_URL}}/student/add
Content-Type: application/json

{

    "name":"Sulav",
    "age": "22"
}

###